export interface Doctor {
    id: string;
    name: string;
    nameBn: string;
    designation: string;
    designationBn: string;
    qualifications?: string;
    qualificationsBn?: string;
    specialty: string;
    specialtyBn: string;
    mobile?: string;
    room?: string;
    roomBn?: string;
    schedule: string;
    scheduleBn: string;
}

export const doctors: Doctor[] = [
    {
        id: "1",
        name: "Dr. Mir Sadequr Rahman",
        nameBn: "ডাঃ মীর সাদেজুর রহমান",
        designation: "Consultant Medicine",
        designationBn: "কনসালটেন্ট মেডিসিন",
        qualifications: "MBBS (DU), CCD (BIRDEM), PGT in Medicine (BSMMU)",
        qualificationsBn: "এমবিবিএস (ডিইউ), সিসিডি (বারডেম), পিজিটি ইন মেডিসিন (বিএসএমএমইউ)",
        specialty: "Medicine",
        specialtyBn: "মেডিসিন",
        mobile: "01841-278222",
        room: "303",
        roomBn: "৩০৩",
        schedule: "Sun, Mon & Wed (8:00 AM - 2:30 PM)",
        scheduleBn: "রবি, সোম ও বুধবার (সকাল ৮.০০ থেকে অপরাহ্ ২.৩০)"
    },
    {
        id: "2",
        name: "Dr. Imam Kownin",
        nameBn: "ডাঃ ইমাম কৌনাইন",
        designation: "Diabetologist",
        designationBn: "ডায়াবেটোলজিস্ট",
        specialty: "Diabetes",
        specialtyBn: "ডায়াবেটিস",
        mobile: "01757-082371",
        room: "304",
        roomBn: "৩০৪",
        schedule: "Sat, Mon & Wed (9:30 AM - 2:00 PM)",
        scheduleBn: "শনি, সোম ও বুধবার (সকাল ৯.৩০ থেকে অপরাহ্ ২.০০)"
    },
    {
        id: "3",
        name: "Dr. Rayana Rahman",
        nameBn: "ডাঃ রায়না রহমান",
        designation: "Consultant, Diabetes",
        designationBn: "কনসালটেন্ট, ডায়াবেটিস",
        qualifications: "MBBS (DU), CCD (BIRDEM)",
        qualificationsBn: "এমবিবিএস (ডিইউ), সিসিডি (বারডেম)",
        specialty: "Diabetes",
        specialtyBn: "ডায়াবেটিস",
        mobile: "01710-534831",
        room: "304",
        roomBn: "৩০৪",
        schedule: "Sun, Tue & Thu (8:00 AM - 2:30 PM)",
        scheduleBn: "রবি, মঙ্গল ও বৃহস্পতিবার (সকাল ৮.০০ থেকে অপরাহ্ ২.৩০)"
    },
    {
        id: "4",
        name: "Dr. Rumana Akter",
        nameBn: "ডাঃ রুমানা আক্তার",
        designation: "Consultant Sonologist",
        designationBn: "কনসালটেন্ট সোনোলজিস্ট",
        qualifications: "MBBS, PGT (Gynae & Obs), DMU",
        qualificationsBn: "এমবিবিএস, পিজিটি (গাইনী এন্ড অবস্), ডিএমইউডি",
        specialty: "Sonology",
        specialtyBn: "সোনোলজি",
        mobile: "01949-112055",
        room: "310",
        roomBn: "৩১০",
        schedule: "Sun & Wed (9:00 AM - 12:00 PM)",
        scheduleBn: "রবিবার ও বুধবার (সকাল ০৯.০০-১২.০০)"
    },
    {
        id: "5",
        name: "Dr. Md. Nafizur Rahman",
        nameBn: "ডাঃ মোঃ নাফিসুর রহমান",
        designation: "Senior Consultant, Cardiologist",
        designationBn: "সিনিয়র কনসালটেন্ট, কার্ডিওলজিস্ট",
        qualifications: "MBBS (Dhaka), D-Card (DU)",
        qualificationsBn: "এমবিবিএস (ঢাকা), ডি কার্ড (ডিইউ)",
        specialty: "Cardiology",
        specialtyBn: "কার্ডিওলজি",
        mobile: "01819-434939",
        room: "307",
        roomBn: "৩০৭",
        schedule: "Sat-Thu (except Fri) (10:00 AM - 2:00 PM)",
        scheduleBn: "শনি, রবি, মঙ্গল, বুধ ও বৃহস্পতিবার (সকাল ১০.০০ থেকে অপরাহ্ ০২.০০)"
    },
    {
        id: "6",
        name: "Dr. Md. Nurul Huda",
        nameBn: "ডাঃ মোঃ নুরুল হুদা",
        designation: "Eye Specialist & Surgeon",
        designationBn: "চক্ষু বিশেষজ্ঞ ও সার্জন",
        qualifications: "MBBS, DO (Dhaka)",
        qualificationsBn: "এমবিবিএস, ডিও (ঢাকা)",
        specialty: "Ophthalmology",
        specialtyBn: "চক্ষু",
        mobile: "01716-089897",
        room: "301",
        roomBn: "৩০১",
        schedule: "Sat-Thu (8:00 AM - 2:30 PM)",
        scheduleBn: "শনি-বৃহস্পতিবার (সকাল ০৮.০০ থেকে অপরাহ্ ০২.৩০)"
    },
    {
        id: "7",
        name: "Dr. Muhammad Kamrul Hasan",
        nameBn: "ডাঃ মুহাম্মদ কামরুল হাসান",
        designation: "Pain, Paralysis & Sports Injury Specialist",
        designationBn: "বাত-ব্যাথা, প্যারালাইসিস ও স্পোর্টস ইনজুরি বিশেষজ্ঞ",
        qualifications: "MBBS, FCPS (Physical Medicine & Rehabilitation)",
        qualificationsBn: "এমবিবিএস, এফসিপিএস (ফিজিক্যাল মেডিসিন এন্ড রিহ্যাবিলিটেশন)",
        specialty: "Physical Medicine",
        specialtyBn: "ফিজিক্যাল মেডিসিন",
        mobile: "01816-320739",
        room: "306",
        roomBn: "৩০৬",
        schedule: "Sat-Thu (8:00 AM - 2:30 PM)",
        scheduleBn: "শনি-বৃহস্পতিবার (সকাল ০৮.০০ থেকে অপরাহ্ ০২.৩০)"
    },
    {
        id: "8",
        name: "Dr. Md. G.M. Mehedi Hasan",
        nameBn: "ডাঃ মোঃ জি.এম. মেহেদী হাসান",
        designation: "Consultant (ENT)",
        designationBn: "কনসালটেন্ট (নাক, কান ও গলা)",
        qualifications: "MBBS, FCPS-2 (ENT)",
        qualificationsBn: "এমবিবিএস, এফসিপিএস-২ (ইএনটি)",
        specialty: "ENT",
        specialtyBn: "নাক, কান ও গলা",
        room: "302",
        roomBn: "৩০২",
        schedule: "Sat-Thu (8:00 AM - 2:30 PM)",
        scheduleBn: "শনি-বৃহস্পতিবার (সকাল ০৮.০০ থেকে অপরাহ্ ০২.৩০)"
    },
    {
        id: "9",
        name: "Dr. Major Mohammad Humayun (Retd.)",
        nameBn: "ডাঃ মেজর মোহাম্মদ হুমায়ুন (অব.)",
        designation: "Pathologist",
        designationBn: "প্যাথলজিস্ট",
        qualifications: "MBBS, MCPS (Clinical Pathology), FCPS (Hematology)",
        qualificationsBn: "এমবিবিএস, এমসিপিএস (ক্লিনি-প্যাথলজিস্ট) এফসিপিএস (হেমাটোলজি)",
        specialty: "Pathology",
        specialtyBn: "প্যাথলজি",
        room: "Pathology",
        roomBn: "প্যাথলজী",
        schedule: "Sat-Thu (1:00 PM - 2:30 PM)",
        scheduleBn: "শনি-বৃহস্পতিবার (দুপুর ০১.০০ থেকে অপরাহ্ ০২.৩০)"
    },
    {
        id: "10",
        name: "Dr. Shamima Haydar",
        nameBn: "ডাঃ শামীমা হায়দার",
        designation: "Consultant (Gynaecology)",
        designationBn: "কনসালটেন্ট (গাইনোকলজি)",
        specialty: "Gynaecology",
        specialtyBn: "গাইনোকলজি",
        mobile: "01711-526062",
        schedule: "Sat, Sun, Mon, Wed, Thu (9:00 AM - 2:00 PM)",
        scheduleBn: "শনি, রবি, সোম, বুধ ও বৃহস্পতিবার (সকাল ৯.০০ থেকে অপরাহ্ ২.০০)"
    },
    {
        id: "11",
        name: "Dr. Rashedul Hasan",
        nameBn: "ডাঃ রাশেদুল হাসান",
        designation: "ENT Specialist",
        designationBn: "নাক, কান ও গলা বিশেষজ্ঞ",
        qualifications: "MBBS, MS (Thesis)",
        qualificationsBn: "এমবিবিএস, এমএসসি, (থিসিস)",
        specialty: "ENT",
        specialtyBn: "নাক, কান ও গলা",
        mobile: "01714-096628",
        room: "302",
        roomBn: "৩০২",
        schedule: "Sat-Thu (8:00 AM - 2:30 PM)",
        scheduleBn: "শনি-বৃহস্পতিবার (সকাল ০৮.০০ থেকে অপরাহ্ ০২.৩০)"
    },
    {
        id: "12",
        name: "Dr. Md. Selim Iftikhar",
        nameBn: "ডাঃ মোঃ সেলিম ইফতিখার",
        designation: "Dentist",
        designationBn: "ডেন্টিস্ট",
        qualifications: "MBBS (Dhaka Dental), PGT (Oral & Maxilla), PGT (Orthodontics)",
        qualificationsBn: "এমবিবিএস (ঢাকা ডেন্টাল), পিজিটি (ওরাল এন্ড ম্যাক্সি), পিজিটি (অর্থোডন্টিক্স)",
        specialty: "Dentistry",
        specialtyBn: "ডেন্টিস্ট্রি",
        mobile: "01674-556957",
        room: "311",
        roomBn: "৩১১",
        schedule: "Sat-Thu (8:00 AM - 2:30 PM)",
        scheduleBn: "শনি-বৃহস্পতিবার (সকাল ০৮.০০ থেকে অপরাহ্ ০২.৩০)"
    },
    {
        id: "13",
        name: "Professor Dr. Md. Azizur Rahman",
        nameBn: "প্রফেসর ডাঃ মোঃ আজিজুর রহমান",
        designation: "Consultant, Chest Disease",
        designationBn: "কনসালটেন্ট, বক্ষব্যাধি",
        qualifications: "MBBS, MD (Chest Disease), FCCP (USA), MCCP (Nepal), FRTMS (Netherlands)",
        qualificationsBn: "এমবিবিএস, এমডি (বক্ষব্যাধি), এফসিসিপি (ইউএসএ) এমসিসিপি (নেপাল), এফডব্লিউএএমএস (নেদারল্যান্ডস)",
        specialty: "Chest Disease",
        specialtyBn: "বক্ষব্যাধি",
        mobile: "01715-363261",
        room: "305",
        roomBn: "৩০৫",
        schedule: "Sat, Mon (8:00 AM - 2:30 PM)",
        scheduleBn: "শনি, সোম (সকাল ০৮.০০ থেকে অপরাহ্ ০২.৩০)"
    },
    {
        id: "14",
        name: "Dr. Nahid Akter",
        nameBn: "ডাঃ নাহিদ আক্তার",
        designation: "Kidney Disease Specialist, Consultant, Nephrology",
        designationBn: "কিডনি রোগ বিশেষজ্ঞ কনসালটেন্ট, নেফ্রোলজি",
        qualifications: "MBBS, MD (Kidney Disease)",
        qualificationsBn: "এমবিবিএস, এমডি (কিডনি রোগ)",
        specialty: "Nephrology",
        specialtyBn: "নেফ্রোলজি",
        mobile: "01922-241616",
        room: "207",
        roomBn: "২০৭",
        schedule: "Sun, Tue (10:00 AM - 2:00 PM)",
        scheduleBn: "রবিবার, মঙ্গলবার : (সকাল ১০:০০ থেকে অপরাহ্ ০২:০০)"
    },
    {
        id: "15",
        name: "Dr. Abdullah Al-Imran",
        nameBn: "ডাঃ আব্দুল্লাহ আল-ইমরান",
        designation: "Emergency Medical Officer",
        designationBn: "জরুরি মেডিকেল অফিসার",
        qualifications: "MBBS (DU), PGT (Medicine)",
        qualificationsBn: "এমবিবিএস (ডিইউ), পিজিটি (মেডিসিন)",
        specialty: "Emergency Medicine",
        specialtyBn: "জরুরি মেডিসিন",
        mobile: "01726-276977",
        room: "103",
        roomBn: "১০৩",
        schedule: "Sat-Thu (8:00 AM - 2:30 PM)",
        scheduleBn: "শনি-বৃহস্পতিবার (সকাল ০৮.০০ থেকে অপরাহ্ ০২.৩০)"
    },
    {
        id: "16",
        name: "Prof. Dr. Hapi Haque",
        nameBn: "প্রফেসর ডাঃ হ্যাপি হক",
        designation: "Cancer Specialist",
        designationBn: "ক্যান্সার বিশেষজ্ঞ",
        qualifications: "MBBS, M.Phil (Clinical Oncology)",
        qualificationsBn: "এমবিবিএস, এম.ফিল (ক্লিনিক্যাল অনকোলজি)",
        specialty: "Oncology",
        specialtyBn: "অনকোলজি",
        mobile: "01711-862738",
        room: "305",
        roomBn: "৩০৫ (Specialized Training)",
        schedule: "Tue, Thu (8:00 AM - 2:30 PM)",
        scheduleBn: "মঙ্গলবার, বৃহস্পতিবার (সকাল ০৮.০০ থেকে অপরাহ্ ০২.৩০)"
    },
    {
        id: "17",
        name: "Dr. Nadira Sultana",
        nameBn: "ডাঃ নাদিরা সুলতানা",
        designation: "Consultant, Neuro Medicine",
        designationBn: "কনসালটেন্ট, নিউরো মেডিসিন",
        qualifications: "MBBS, MD (Neurology)",
        qualificationsBn: "এমবিবিএস, এমডি (নিউরোলজি)",
        specialty: "Neurology",
        specialtyBn: "নিউরোলজি",
        mobile: "01713-392528",
        room: "206",
        roomBn: "২০৬",
        schedule: "Sun & Wed (10:00 AM - 2:00 PM)",
        scheduleBn: "রবি ও বুধবার (সকাল ১০.০০ থেকে অপরাহ্ ২.০০)"
    },
    {
        id: "18",
        name: "Dr. Anisur Rahman",
        nameBn: "ডাঃ আনিসুর রহমান",
        designation: "Consultant, Endocrinology",
        designationBn: "কনসালটেন্ট, এনডোক্রাইনোলজি",
        qualifications: "DM, MD (Endocrinology), FCPS",
        qualificationsBn: "ডিএম, এমডি (এনডোক্রাইনোলজি), এফএসিই",
        specialty: "Endocrinology",
        specialtyBn: "এনডোক্রাইনোলজি",
        mobile: "01715-160040",
        room: "206",
        roomBn: "২০৬",
        schedule: "Mon, Thu (10:00 AM - 2:00 PM)",
        scheduleBn: "সোমবার, বৃহস্পতিবার (সকাল ১০:০০ থেকে অপরাহ্ ২:০০)"
    },
    {
        id: "19",
        name: "Professor Dr. Md. Amanur Rasul",
        nameBn: "অধ্যাপক ডাঃ মো: আমানুর রসুল",
        designation: "Urine, Sex, Kidney & Prostate Specialist Surgeon",
        designationBn: "মূত্র, যৌন, কিডনী রোগ ও প্রোস্টেট বিশেষজ্ঞ সার্জন",
        qualifications: "MBBS, MS (Urology)",
        qualificationsBn: "এমবিবিএস, এমএস (ইউরোলজি)",
        specialty: "Urology",
        specialtyBn: "ইউরোলজি",
        room: "305",
        roomBn: "৩০৫",
        schedule: "Thu (4:00 PM - 6:00 PM)",
        scheduleBn: "প্রতি বৃহস্পতিবার (অপরাহ্ ৪.০০- সন্ধ্যা ৬.০০)"
    },
    {
        id: "20",
        name: "Dr. Md. Riad Ahmed",
        nameBn: "ডাঃ মোঃ রিয়াদ আহমেদ",
        designation: "Medical Officer",
        designationBn: "মেডিকেল অফিসার",
        qualifications: "MBBS",
        qualificationsBn: "এমবিবিএস",
        specialty: "General Medicine",
        specialtyBn: "জেনারেল মেডিসিন",
        mobile: "01581-082941",
        room: "103",
        roomBn: "১০৩",
        schedule: "Sat-Thu (2:00 PM - 6:00 PM)",
        scheduleBn: "শনি-বৃহস্পতিবার (দুপুর ২.০০ থেকে সন্ধ্যা ৬.০০)"
    }
];
